export interface BibleBook {
    id: string;
    cnName: string;
    enName: string;
    chapters: number;
    testament: 'OT' | 'NT';
}

export const bibleBooks: BibleBook[] = [
    // Old Testament
    { id: "GEN", cnName: "創世記", enName: "Genesis", chapters: 50, testament: "OT" },
    { id: "EXO", cnName: "出埃及記", enName: "Exodus", chapters: 40, testament: "OT" },
    { id: "LEV", cnName: "利未記", enName: "Leviticus", chapters: 27, testament: "OT" },
    { id: "NUM", cnName: "民數記", enName: "Numbers", chapters: 36, testament: "OT" },
    { id: "DEU", cnName: "申命記", enName: "Deuteronomy", chapters: 34, testament: "OT" },
    { id: "JOS", cnName: "約書亞記", enName: "Joshua", chapters: 24, testament: "OT" },
    { id: "JDG", cnName: "士師記", enName: "Judges", chapters: 21, testament: "OT" },
    { id: "RUT", cnName: "路得記", enName: "Ruth", chapters: 4, testament: "OT" },
    { id: "1SA", cnName: "撒母耳記上", enName: "1 Samuel", chapters: 31, testament: "OT" },
    { id: "2SA", cnName: "撒母耳記下", enName: "2 Samuel", chapters: 24, testament: "OT" },
    { id: "1KI", cnName: "列王紀上", enName: "1 Kings", chapters: 22, testament: "OT" },
    { id: "2KI", cnName: "列王紀下", enName: "2 Kings", chapters: 25, testament: "OT" },
    { id: "1CH", cnName: "歷代志上", enName: "1 Chronicles", chapters: 29, testament: "OT" },
    { id: "2CH", cnName: "歷代志下", enName: "2 Chronicles", chapters: 36, testament: "OT" },
    { id: "EZR", cnName: "以斯拉記", enName: "Ezra", chapters: 10, testament: "OT" },
    { id: "NEH", cnName: "尼希米記", enName: "Nehemiah", chapters: 13, testament: "OT" },
    { id: "EST", cnName: "以斯帖記", enName: "Esther", chapters: 10, testament: "OT" },
    { id: "JOB", cnName: "約伯記", enName: "Job", chapters: 42, testament: "OT" },
    { id: "PSA", cnName: "詩篇", enName: "Psalms", chapters: 150, testament: "OT" },
    { id: "PRO", cnName: "箴言", enName: "Proverbs", chapters: 31, testament: "OT" },
    { id: "ECC", cnName: "傳道書", enName: "Ecclesiastes", chapters: 12, testament: "OT" },
    { id: "SNG", cnName: "雅歌", enName: "Song of Solomon", chapters: 8, testament: "OT" },
    { id: "ISA", cnName: "以賽亞書", enName: "Isaiah", chapters: 66, testament: "OT" },
    { id: "JER", cnName: "耶利米書", enName: "Jeremiah", chapters: 52, testament: "OT" },
    { id: "LAM", cnName: "耶利米哀歌", enName: "Lamentations", chapters: 5, testament: "OT" },
    { id: "EZK", cnName: "以西結書", enName: "Ezekiel", chapters: 48, testament: "OT" },
    { id: "DAN", cnName: "但以理書", enName: "Daniel", chapters: 12, testament: "OT" },
    { id: "HOS", cnName: "何西阿書", enName: "Hosea", chapters: 14, testament: "OT" },
    { id: "JOL", cnName: "約珥書", enName: "Joel", chapters: 3, testament: "OT" },
    { id: "AMO", cnName: "阿摩司書", enName: "Amos", chapters: 9, testament: "OT" },
    { id: "OBA", cnName: "俄巴底亞書", enName: "Obadiah", chapters: 1, testament: "OT" },
    { id: "JON", cnName: "約拿書", enName: "Jonah", chapters: 4, testament: "OT" },
    { id: "MIC", cnName: "彌迦書", enName: "Micah", chapters: 7, testament: "OT" },
    { id: "NAM", cnName: "那鴻書", enName: "Nahum", chapters: 3, testament: "OT" },
    { id: "HAB", cnName: "哈巴谷書", enName: "Habakkuk", chapters: 3, testament: "OT" },
    { id: "ZEP", cnName: "西番雅書", enName: "Zephaniah", chapters: 3, testament: "OT" },
    { id: "HAG", cnName: "哈該書", enName: "Haggai", chapters: 2, testament: "OT" },
    { id: "ZEC", cnName: "撒迦利亞書", enName: "Zechariah", chapters: 14, testament: "OT" },
    { id: "MAL", cnName: "瑪拉基書", enName: "Malachi", chapters: 4, testament: "OT" },

    // New Testament
    { id: "MAT", cnName: "馬太福音", enName: "Matthew", chapters: 28, testament: "NT" },
    { id: "MRK", cnName: "馬可福音", enName: "Mark", chapters: 16, testament: "NT" },
    { id: "LUK", cnName: "路加福音", enName: "Luke", chapters: 24, testament: "NT" },
    { id: "JHN", cnName: "約翰福音", enName: "John", chapters: 21, testament: "NT" },
    { id: "ACT", cnName: "使徒行傳", enName: "Acts", chapters: 28, testament: "NT" },
    { id: "ROM", cnName: "羅馬書", enName: "Romans", chapters: 16, testament: "NT" },
    { id: "1CO", cnName: "哥林多前書", enName: "1 Corinthians", chapters: 16, testament: "NT" },
    { id: "2CO", cnName: "哥林多後書", enName: "2 Corinthians", chapters: 13, testament: "NT" },
    { id: "GAL", cnName: "加拉太書", enName: "Galatians", chapters: 6, testament: "NT" },
    { id: "EPH", cnName: "以弗所書", enName: "Ephesians", chapters: 6, testament: "NT" },
    { id: "PHP", cnName: "腓立比書", enName: "Philippians", chapters: 4, testament: "NT" },
    { id: "COL", cnName: "歌羅西書", enName: "Colossians", chapters: 4, testament: "NT" },
    { id: "1TH", cnName: "帖撒羅尼迦前書", enName: "1 Thessalonians", chapters: 5, testament: "NT" },
    { id: "2TH", cnName: "帖撒羅尼迦後書", enName: "2 Thessalonians", chapters: 3, testament: "NT" },
    { id: "1TI", cnName: "提摩太前書", enName: "1 Timothy", chapters: 6, testament: "NT" },
    { id: "2TI", cnName: "提摩太後書", enName: "2 Timothy", chapters: 4, testament: "NT" },
    { id: "TIT", cnName: "提多書", enName: "Titus", chapters: 3, testament: "NT" },
    { id: "PHM", cnName: "腓利門書", enName: "Philemon", chapters: 1, testament: "NT" },
    { id: "HEB", cnName: "希伯來書", enName: "Hebrews", chapters: 13, testament: "NT" },
    { id: "JAS", cnName: "雅各書", enName: "James", chapters: 5, testament: "NT" },
    { id: "1PE", cnName: "彼得前書", enName: "1 Peter", chapters: 5, testament: "NT" },
    { id: "2PE", cnName: "彼得後書", enName: "2 Peter", chapters: 3, testament: "NT" },
    { id: "1JN", cnName: "約翰一書", enName: "1 John", chapters: 5, testament: "NT" },
    { id: "2JN", cnName: "約翰二書", enName: "2 John", chapters: 1, testament: "NT" },
    { id: "3JN", cnName: "約翰三書", enName: "3 John", chapters: 1, testament: "NT" },
    { id: "JUD", cnName: "猶大書", enName: "Jude", chapters: 1, testament: "NT" },
    { id: "REV", cnName: "啟示錄", enName: "Revelation", chapters: 22, testament: "NT" }
];
